---
# name: ansible-roles
# file: inventory/host_vars/docker.yml

meta_description: 'Ansible role for setting up docker from os repositories.'

meta_galaxy_tags:
  - docker
  - compose

meta_year_created: '2021'

read_description: |
  Installs docker from system packages on supported systems and optionally
  writes a docker daemon configuration file.
