---
# name: ansible-roles
# file: inventory/group_vars/all/molecule.yml

meta_molecule_playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml

meta_molecule_prepare: |
  - name: "PLAYBOOK | Prepare"
    hosts: all
    become: true
    gather_facts: true
    tasks:
      - name: "Update apk cache and installed packages"
        community.general.apk:
          available: true
          update_cache: true
          upgrade: true
        when: ansible_pkg_mgr == "apk"

      - name: "Update apt cache and installed packages"  # noqa: package-latest
        ansible.builtin.apt:
          force_apt_get: true
          state: latest
          update_cache: true
        when: ansible_pkg_mgr == "apt"

      - name: "Update dnf cache and installed packages"  # noqa: package-latest
        ansible.builtin.dnf:
          name: "*"
          state: latest
          update_cache: true
        when: ansible_pkg_mgr == "dnf"

      - name: "Update pacman cache and installed packages"
        community.general.pacman:
          update_cache: true
          upgrade: true
        when: ansible_pkg_mgr == "pacman"

      - name: "Update yum cache and installed packages"  # noqa: package-latest
        ansible.builtin.yum:
          name: "*"
          state: latest
          update_cache: true
        when: ansible_pkg_mgr == "yum"

      - name: "Update zypper cache and installed packages"  # noqa: package-latest
        community.general.zypper:
          name: "*"
          state: latest
          update_cache: true
        when: ansible_pkg_mgr == "zypper"
